version: "3.7"
services:
  create-json:
    image: create-json:latest
    build:
      context: .
      dockerfile: create-json.dockerfile
    environment:
      - SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
      - GEOCODING_API_KEY=${GOOGLE_GEOCODING_API_KEY}
    volumes:
      - ".:/app"
      - "./src/waypoints.json:/app/build/static/waypoints.json"
      - "/app/node_modules"
  host-frontend:
    image: host-frontend:latest
    build:
      context: .
      dockerfile: host-frontend.dockerfile
    volumes:
      - "./src/waypoints.json:/app/static/waypoints.json"
    ports:
      - "5000:80"
